### PR TITLE
controller: read/write timeout

### PR DESCRIPTION
**Pull request by kp6**
- implemented "per request" read/write timeout
- replica ping is disabled

### CODE REVIEW

**Comment by yasker** [comment]
Use sleep to count the timeout seems a little weird to me.

I think we should able to replace the wait group [here]( https://github.com/rancher/longhorn/blob/master/rpc/client.go#L59 ) for a channel, then implement the typical [go time out pattern](https://blog.golang.org/go-concurrency-patterns-timing-out-and). This way seems more straightforward to me.

**Comment by kp6** [comment]
@yasker you may be right, let me check if that's the case

**Comment by kp6** [comment]
@yasker let me know if that's what you had in mind, I'll squash/rebase then

**Comment by yasker** [comment]
@kp6 

Yes, that's exactly what I have in mind.

Looks good to me. Thanks.

**Comment by kp6** [comment]
squashed/rebased

**Comment by yasker** [comment]
@kp6 

You can just get rid of all ping timeout code in the second patch. If anything goes wrong we still can easily revert back.

**Comment by kp6** [comment]
@yasker per your suggestion I amended the last commit

**Comment by yasker** [comment]
@kp6 

You missed a bunch of code for ping. Better take a look at https://github.com/rancher/longhorn/commit/90f7a6cedf0a3a245574ea0c6cf346926f934356 , which added ping logic.

**Comment by kp6** [comment]
looking...

**Comment by kp6** [comment]
@yasker amended the ping removal; thanks for catching the un-reverted pieces

**Comment by yasker** [comment]
Merged, thanks.

**Pull request merged**
