### PR TITLE
Controller: Rw timeout with stats

### PR DESCRIPTION
**Pull request by kp6**
this is a rework of PR https://github.com/rancher/longhorn/pull/112

Use this PR for review: https://github.com/kp6/longhorn/pull/2

### CODE REVIEW

**Comment by kp6** [comment]
rebased on https://github.com/rancher/longhorn/pull/116

**Comment by yasker** [comment]
1. I think we can have the same sample point as in timeout patch, in RPC code.
2. I agree with @ibuildthecloud on his comment for go-metrics. We should use common library instead of writing our own on metrics as much as possible. It's good for now and long run.

**Comment by kp6** [comment]
1. If I understand you right, you meant `rpc/client.go` and a location like `func (c *Client) operation(op uint32, buf []byte, offset int64) (int, error)...`?

- the issue I have with that suggestion is the absence of context like a replica index there. We need to identify pending operations belonging to different replicas with a replica index or something. And that is not available at this level. 
- Does that make sense or am i missing something?

2. Yes. I'll be looking at the `go-metrics` it is just I haven't figured out how to achieve "on-demand" metrics flushing there.

**Comment by yasker** [comment]
From `conn` or `wire` you can have peer IP.

**Comment by kp6** [comment]
I liked concise nature of the current use of the replica index but it also has it's flaws as it does not really identify replicas if they are removde and added back.  So I'll look into the possible use of the IP...

**Comment by kp6** [comment]
@yasker I addressed (1) you brought in https://github.com/rancher/longhorn/pull/118#issuecomment-223449062 in this commit: d416a74
take a look, when you get a chance. I'll squash and reshuffle commits after

**Comment by kp6** [comment]
rebased

**Pull request closed without merging**
